block.settings.hello_hello:
  type: block_settings
  label: 'Hello block'
  mapping:
    example:
      type: string
      label: Example

# Schema for the configuration files of the Hello module.
hello.settings:
  type: config_object
  label: 'Hello settings'
  mapping:
    example:
      type: string
      label: 'Example'
